# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: 'en'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false       # Allows optimizing the container by removing unused services; this also means
                            # fetching services directly from the container via $container->get() won't work.
                            # The best practice is to be explicit about your dependencies anyway.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    admin.user:
        class: App\Admin\UserAdmin
        arguments: [~, App\Entity\User, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Usuarios, label: Usuario }
        public: true

    admin.grupo-universidad:
            class: App\Admin\GruposAdmin
            arguments: [~, App\Entity\Grupo, ~]
            tags:
                - { name: sonata.admin, manager_type: orm, group: Grupos, label: Universidades }
            public: true

    admin.grupo-colegio:
            class: App\Admin\GruposColegioAdmin
            arguments: [~, App\Entity\GrupoColegio, ~]
            tags:
                - { name: sonata.admin, manager_type: orm, group: Grupos, label: Colegios }
            public: true

    admin.universidad:
            class: App\Admin\UniversidadAdmin
            arguments: [~, App\Entity\Universidad,~ ]
            tags:
                - { name: sonata.admin, manager_type: orm, group: Misc, label: Universidad }
            public: true

    admin.especialidad:
            class: App\Admin\EspecialidadAdmin
            arguments: [~, App\Entity\Especialidad, ~]
            tags:
                - { name: sonata.admin, manager_type: orm, group: Misc, label: Especialidad }
            public: true

    admin.colegio:
            class: App\Admin\ColegioAdmin
            arguments: [~, App\Entity\Colegio, ~]
            tags:
                - { name: sonata.admin, manager_type: orm, group: Misc, label: Colegio }
            public: true


#    app.admin.grupos_usuarios:
#        class: AppBundle\Admin\GruposUsuariosAdmin
#        arguments: [~, AppBundle\Entity\GruposUsuarios, SonataAdminBundle:CRUD]
#        tags:
#            - { name: sonata.admin, manager_type: orm, group: Usuarios, label: Usuarios por Grupo }
#        public: true



